version: '2'

services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      # - "/etc/selenoid:/etc/selenoid:ro"
      # - "//var/run/docker.sock:/var/run/docker.sock"
      - ".:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4444:4444"
    command: -limit 2 -conf /etc/selenoid/browsers.json
    