version: '3'

services:
  selenoid:
    image: "aerokube/selenoid:1.6.0"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "$PWD:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
    #environment:
    #  - DOCKER_API_VERSION="1.35" # when errors like current docker version should be ...
    command: ["-conf", "/etc/selenoid/browsers.json", "-limit", "4"]
